import Footer from "@/Components/Footer/Footer";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className=" flex flex-col min-h-screen">
        <Navbar></Navbar>

        <main className="flex-1">
          {children}
        </main>

        <Footer></Footer>
      </body>
    </html>
  );
}
